question_data = [
    {
        "category": "Politics",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Denmark has a monarch.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The Lego Group was founded in 1932.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In Terraria, you can craft the Cell Phone pre-hardmode.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In Pokeamon, Arbok evolves into Seviper.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Cartoon & Animations",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Waylon Smithers from 'The Simpsons' was originally black when he first appeared in the series.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In the 'S.T.A.L.K.E.R.' series, the Freedom faction wishes to destroy the supernatural area known as the Zone&quot;.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science & Nature",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Water always boils at 100C, 212F, 373.15K, no matter where you are.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Rhode Island is actually located on the US mainland, despite its name.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In the video game Splatoon, the playable characters were originally going to be rabbits instead of squids.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Animals",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The freshwater amphibian, the Axolotl, can regrow limbs.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
]
